### ISSUE TITLE
won't load

### ISSUE THREAD

**Issue by justin69321** [jdaster64/ttyd-tot#2]
i tried booting it and it won't load

**Comment by jdaster64** [comment]
Please provide more background. What platform are you running on?  Do you have issues running an unmodified copy of TTYD?  Are you attempting to run the game with additional codes or mods that are likely incompatible?

**Comment by justin69321** [comment]
i'm on windows 11 try to patch the rom to use it on dolphin on android

**Comment by justin69321** [comment]
I tend to run the game on dolphin via android. The normal game works fine.
Everything is off

**Comment by jdaster64** [comment]
Just tested on my Android device, and the patched ISO boots and gets to gameplay fine.  Please double-check that you have an up-to-date version of the emulator, that you correctly patched the ISO, and have no additional Gecko codes or other types of mods applied for Paper Mario: The Thousand-Year Door's game id.  Closing as irreproducible.

**Comment by justin69321** [comment]
Ok. I'll get to that

**Comment by justin69321** [comment]
I need to get mine patched but the application don't work

**Comment by jdaster64** [comment]
Confirmed working for multiple other Win11 users.

**Comment by justin69321** [comment]
Ok. It won't work for me. This is weird. How can I get it to work?
