### ISSUE TITLE
Sequence break on first Gloomtail's Tower run

### ISSUE THREAD

**Issue by CaccHunter** [jdaster64/ttyd-tot#3]
1) Beat Hooktail for the first time.
2) Start the first Gloomtail's Tower run.
3) Die. (I don't know if it matters what floor you die on, but I don't think it matters.)
4) Retry. (as in return to the room that bridges the hub and the castle)
5) Enter the castle again.
6) Get to floor 32 and be surprised to see Hooktail again.
7) Beat Hooktail.
8) The game acts like you just beat Gloomtail and puts you in the "post-story" state, including the first Koopa talking about how you beat Gloomtail and all the other hub stuff updating.

It doesn't really cause any problems. I suspect it has something to do with the new feature where new runs default to Hooktail's Tower.

**Comment by jdaster64** [comment]
What version did you start the run on?  This bug was introduced on v1.10, but should be fixed if starting a second run on the most recent patch.

**Comment by CaccHunter** [comment]
It was v1.10. Sorry about that.
