### ISSUE TITLE
Getting Virus Warning

### ISSUE THREAD

**Issue by TravelocityKirby** [jdaster64/ttyd-tot#4]
Tried downloading both the latest patcher and the one before it through Chrome on an Acer Nitro with Windows 11 to use for Dolphin and both it and McAfee keep giving me a virus detection warning, blocking it. The threat was listed as "ti!94e7f655220c"

**Comment by jdaster64** [comment]
You'll need to make an exception for it, then.

**Comment by jdaster64** [comment]
You'll need to make an exception for it, then.
