### ISSUE TITLE
Game froze after using boo's sheet in midboss. Ver. 1 15 r43

### ISSUE THREAD

**Issue by TigerCatMichael** [jdaster64/ttyd-tot#7]
I am in fullscreen mode, if that means anything.
dolphin is still open, and there is no crash message. it just stopped.
![image](https://github.com/user-attachments/assets/122a3371-cc28-419e-86b5-7ab1e1cd543f)

**Comment by jdaster64** [comment]
Try using a different graphics backend; it's not likely to be reproducible on other machines.
