### ISSUE TITLE
Wrong Room Colours After Reload

### ISSUE THREAD

**Issue by DogShrapnel** [jdaster64/ttyd-tot#8]
As of v2.01 r46, if you're far enough into a tower run that the room colours have changed, if you save and quit then reload, when you enter the next room, it defaults to the original red flooring.
![G8ME01_2024-12-12_22-06-50](https://github.com/user-attachments/assets/c56f4d5e-245d-462a-ad42-9504fae361c7)

**Comment by jdaster64** [comment]
Acknowledged; will address in the next patch if there are any major bugs found in the near future.
